# Generated by Django 5.0.14 on 2025-10-28 14:47

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(default='Din Auktoriserade Redovisningsbyrå', max_length=255, verbose_name='Hero rubrik')),
                ('hero_subtitle', wagtail.fields.RichTextField(blank=True, verbose_name='Hero undertext')),
                ('hero_cta_text', models.CharField(default='Kontakta oss', max_length=100, verbose_name='Knapptext')),
                ('body', wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='title', icon='title', label='Rubrik')), ('paragraph', wagtail.blocks.RichTextBlock(label='Paragraf')), ('image', wagtail.images.blocks.ImageChooserBlock(label='Bild')), ('services', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(label='Rubrik')), ('services', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('icon', wagtail.blocks.CharBlock(help_text='Lucide icon namn (t.ex. calculator, users, file-text)', label='Ikon')), ('title', wagtail.blocks.CharBlock(label='Titel')), ('description', wagtail.blocks.TextBlock(label='Beskrivning'))])))], icon='list-ul', label='Tjänster'))], blank=True, verbose_name='Innehåll')),
                ('show_instagram', models.BooleanField(default=True, verbose_name='Visa Instagram-flöde')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Hero bild')),
            ],
            options={
                'verbose_name': 'Startsida',
            },
            bases=('wagtailcore.page',),
        ),
    ]
