# Generated by Django 5.0.14 on 2025-10-29 09:35

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Introduktion')),
                ('services', wagtail.fields.StreamField([('service', wagtail.blocks.StructBlock([('icon', wagtail.blocks.CharBlock(help_text='Lucide icon namn (t.ex. calculator, users, file-text)', label='Ikon')), ('title', wagtail.blocks.CharBlock(label='Titel')), ('description', wagtail.blocks.TextBlock(label='Beskrivning')), ('features', wagtail.blocks.ListBlock(wagtail.blocks.CharBlock(label='Funktion'), label='Funktioner/Fördelar')), ('price_info', wagtail.blocks.CharBlock(help_text='T.ex. "Från 2000 kr/mån" (valfritt)', label='Prisinformation', required=False)), ('cta_text', wagtail.blocks.CharBlock(default='Läs mer', label='Knapptext')), ('cta_link', wagtail.blocks.URLBlock(label='Knapp-länk (valfritt)', required=False))], icon='briefcase', label='Tjänst'))], blank=True, verbose_name='Tjänster')),
            ],
            options={
                'verbose_name': 'Tjänstesida',
            },
            bases=('wagtailcore.page',),
        ),
    ]
