# Generated by Django 5.2.8 on 2025-11-09 21:59

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_servicespage'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Ingress')),
                ('body', wagtail.fields.StreamField([('richtext', 0)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'ol', 'ul', 'link']})}, verbose_name='Innehåll')),
            ],
            options={
                'verbose_name': 'Om oss-sida',
                'verbose_name_plural': 'Om oss-sidor',
            },
            bases=('wagtailcore.page',),
        ),
    ]
