# Generated by Django 5.2.8 on 2025-11-09 22:39

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aboutpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='Kort beskrivning av företaget (visas på startsidan)', verbose_name='Om oss - Text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_title',
            field=models.CharField(blank=True, default='Om Harpans Redovisning', max_length=255, verbose_name='Om oss - Rubrik'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='value_1_icon',
            field=models.CharField(blank=True, default='heart', help_text='Lucide-ikonnamn', max_length=50, verbose_name='Ikon'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='value_1_text',
            field=models.TextField(blank=True, default='Vi tror på långsiktiga relationer', verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='value_1_title',
            field=models.CharField(blank=True, default='Personlig service', max_length=100, verbose_name='Rubrik'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='value_2_icon',
            field=models.CharField(blank=True, default='shield-check', max_length=50, verbose_name='Ikon'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='value_2_text',
            field=models.TextField(blank=True, default='Inga dolda avgifter', verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='value_2_title',
            field=models.CharField(blank=True, default='Transparens', max_length=100, verbose_name='Rubrik'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='value_3_icon',
            field=models.CharField(blank=True, default='zap', max_length=50, verbose_name='Ikon'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='value_3_text',
            field=models.TextField(blank=True, default='Digitala lösningar', verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='value_3_title',
            field=models.CharField(blank=True, default='Modern teknologi', max_length=100, verbose_name='Rubrik'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('services', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title', 'label': 'Rubrik'}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Paragraf'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Bild'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Rubrik'}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Lucide icon namn (t.ex. calculator, users, file-text)', 'label': 'Ikon'}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Titel'}), 6: ('wagtail.blocks.TextBlock', (), {'label': 'Beskrivning'}), 7: ('wagtail.blocks.StructBlock', [[('icon', 4), ('title', 5), ('description', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {}), 9: ('wagtail.blocks.StructBlock', [[('title', 3), ('services', 8)]], {'icon': 'list-ul', 'label': 'Tjänster'})}, verbose_name='Extra innehåll (valfritt)'),
        ),
        migrations.DeleteModel(
            name='AboutPage',
        ),
    ]
