# Generated by Django 5.2.8 on 2025-11-09 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_homepage_about_text_homepage_about_title_and_more'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_url', models.URLField(blank=True, help_text='URL till bokningssystem (t.ex. Calendly)', verbose_name='Boknings-URL')),
                ('portal_url', models.URLField(blank=True, default='https://kundportal.harpans.se', verbose_name='Kundportal-URL')),
                ('blog_page', models.ForeignKey(blank=True, help_text='Välj blogg-sidan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Blogg-sida')),
                ('contact_page', models.ForeignKey(blank=True, help_text='Välj kontakt-sidan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Kontakt-sida')),
                ('services_page', models.ForeignKey(blank=True, help_text='Välj tjänstesidan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Tjänstesida')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
                ('team_page', models.ForeignKey(blank=True, help_text='Välj team-sidan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Team-sida')),
            ],
            options={
                'verbose_name': 'Navigation',
            },
        ),
    ]
