# Generated by Django 5.2.8 on 2025-11-09 23:54

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_navigationsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='about_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='Kort beskrivning av företaget', verbose_name='Om oss - Text'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('services', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title', 'label': 'Rubrik'}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Paragraf'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Bild'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Rubrik'}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Lucide icon namn', 'label': 'Ikon'}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Titel'}), 6: ('wagtail.blocks.TextBlock', (), {'label': 'Beskrivning'}), 7: ('wagtail.blocks.StructBlock', [[('icon', 4), ('title', 5), ('description', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {}), 9: ('wagtail.blocks.StructBlock', [[('title', 3), ('services', 8)]], {'icon': 'list-ul', 'label': 'Tjänster'})}, verbose_name='Extra innehåll (valfritt)'),
        ),
    ]
