# Generated by Django 5.2.8 on 2025-11-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_homepage_about_text_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={},
        ),
        migrations.AddField(
            model_name='navigationsettings',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Länk till företagets Facebook-sida', verbose_name='Facebook-sida'),
        ),
        migrations.AddField(
            model_name='navigationsettings',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Länk till företagets Instagram-konto', verbose_name='Instagram-profil'),
        ),
        migrations.AddField(
            model_name='navigationsettings',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='Länk till företagets LinkedIn-sida', verbose_name='LinkedIn-profil'),
        ),
        migrations.AddField(
            model_name='navigationsettings',
            name='x_url',
            field=models.URLField(blank=True, help_text='Länk till företagets X-profil', verbose_name='X (före detta Twitter)'),
        ),
    ]
