# Generated by Django 5.2.8 on 2025-11-12 13:27

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_legalpage'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicespage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='Stor toppbild för sidan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Hero-bild'),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='services',
            field=wagtail.fields.StreamField([('service', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Lucide-ikon, t.ex. calculator', 'label': 'Ikon'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Titel'}), 2: ('wagtail.blocks.TextBlock', (), {'label': 'Beskrivning'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Funktion'}), 4: ('wagtail.blocks.ListBlock', (3,), {'label': 'Funktioner/Fördelar'}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Prisinformation', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'default': 'Läs mer', 'label': 'Knapptext'}), 7: ('wagtail.blocks.URLBlock', (), {'label': 'Knapp-länk', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('icon', 0), ('title', 1), ('description', 2), ('features', 4), ('price_info', 5), ('cta_text', 6), ('cta_link', 7)]], {'icon': 'briefcase', 'label': 'Tjänst'})}, verbose_name='Tjänster'),
        ),
    ]
