# Generated by Django 5.2.8 on 2025-11-21 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_servicespage_hero_image_alter_servicespage_services'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicespage',
            name='hero_video',
            field=models.ForeignKey(blank=True, help_text='MP4-video för hero-bakgrund. Lämna tom för att använda bild.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Hero video'),
        ),
    ]
