# Generated by Django 5.2.8 on 2025-12-08 10:13

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_servicespage_hero_video'),
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtaildocs', '0014_alter_document_file_size'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationsettings',
            name='aktuellt_page',
            field=models.ForeignKey(blank=True, help_text='Välj sidan för Aktuellt (Skatteverket-flöde)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Aktuellt-sida'),
        ),
        migrations.CreateModel(
            name='AktuelltPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_lede', models.CharField(blank=True, default='Nyheter, notiser och pressmeddelanden från Skatteverket.', max_length=255, verbose_name='Hero ingress')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Intro (valfritt)')),
                ('feeds', wagtail.fields.StreamField([('feed', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Skatteverket', 'label': 'Rubrik', 'required': False}), 1: ('wagtail.blocks.URLBlock', (), {'label': 'RSS-länk'}), 2: ('wagtail.blocks.IntegerBlock', (), {'default': 12, 'label': 'Antal', 'max_value': 50, 'min_value': 1, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Visas under rubriken', 'label': 'Valfri text (liten notis)', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('feed_url', 1), ('max_items', 2), ('note', 3)]], {})}, verbose_name='Flöden')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Rubrik'}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Text'})}, verbose_name='Extra innehåll (valfritt)')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Hero-bild')),
                ('hero_video', models.ForeignKey(blank=True, help_text='MP4-video för hero-bakgrund. Lämna tom för att använda bild.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Hero video')),
            ],
            options={
                'verbose_name': 'Aktuellt',
            },
            bases=('wagtailcore.page',),
        ),
    ]
