# Generated by Django 5.0.14 on 2025-10-28 14:47

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Introduktion')),
            ],
            options={
                'verbose_name': 'Om oss',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Namn')),
                ('title', models.CharField(max_length=255, verbose_name='Titel/Roll')),
                ('bio', wagtail.fields.RichTextField(blank=True, verbose_name='Biografi')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-post')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Foto')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='team.teampage')),
            ],
            options={
                'verbose_name': 'Teammedlem',
                'verbose_name_plural': 'Teammedlemmar',
            },
        ),
    ]
