# Generated by Django 5.2.8 on 2025-11-07 14:38

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['sort_order'], 'verbose_name': 'Teammedlem', 'verbose_name_plural': 'Teammedlemmar'},
        ),
        migrations.AddField(
            model_name='teammember',
            name='availability_note',
            field=models.CharField(blank=True, help_text="Visar en kort text om tillgänglighet (t.ex. 'Tillbaka 15 januari')", max_length=100, verbose_name='Statusmeddelande'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='availability_status',
            field=models.CharField(choices=[('available', 'Tillgänglig'), ('limited', 'Begränsad tillgänglighet'), ('unavailable', 'Ej tillgänglig'), ('vacation', 'Semester')], default='available', max_length=20, verbose_name='Tillgänglighetsstatus'),
        ),
        migrations.AddField(
            model_name='teampage',
            name='about_content',
            field=wagtail.fields.RichTextField(blank=True, help_text='Beskriv företaget innan teammedlemmarna visas', verbose_name='Om oss-innehåll'),
        ),
        migrations.AddField(
            model_name='teampage',
            name='about_heading',
            field=models.CharField(default='Om oss', max_length=255, verbose_name='Rubrik för Om oss-sektion'),
        ),
    ]
