# Generated by Django 5.2.8 on 2025-11-07 15:04

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_alter_teammember_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teampage',
            options={'verbose_name': 'Team-sida', 'verbose_name_plural': 'Team-sidor'},
        ),
        migrations.RemoveField(
            model_name='teampage',
            name='about_content',
        ),
        migrations.RemoveField(
            model_name='teampage',
            name='about_heading',
        ),
        migrations.AlterField(
            model_name='teammember',
            name='availability_note',
            field=models.CharField(blank=True, max_length=100, verbose_name='Statusmeddelande'),
        ),
        migrations.AlterField(
            model_name='teampage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Intro överst på team-sidan'),
        ),
    ]
