# Generated by Django 5.2.8 on 2025-11-09 21:59

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_alter_teampage_options_remove_teampage_about_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teampage',
            options={'verbose_name': 'Om oss'},
        ),
        migrations.AddField(
            model_name='teampage',
            name='about_content',
            field=wagtail.fields.RichTextField(blank=True, help_text='Beskriv företaget innan teammedlemmarna visas', verbose_name='Om oss-innehåll'),
        ),
        migrations.AddField(
            model_name='teampage',
            name='about_heading',
            field=models.CharField(default='Om oss', max_length=255, verbose_name='Rubrik för Om oss-sektion'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='availability_note',
            field=models.CharField(blank=True, help_text="Visar en kort text om tillgänglighet (t.ex. 'Tillbaka 15 januari')", max_length=100, verbose_name='Statusmeddelande'),
        ),
        migrations.AlterField(
            model_name='teampage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Introduktion'),
        ),
    ]
