# Generated by Django 5.2.8 on 2025-11-09 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_alter_teampage_options_teampage_about_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='calendly_url',
            field=models.URLField(blank=True, help_text='URL till din personliga Calendly-bokningssida (t.ex. https://calendly.com/anna-harpans)', verbose_name='Calendly-länk'),
        ),
    ]
