# Generated by Django 5.2.8 on 2025-11-09 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_teammember_calendly_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'verbose_name': 'Teammedlem'},
        ),
    ]
