# Generated by Django 5.2.8 on 2025-11-09 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_alter_teammember_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['sort_order'], 'verbose_name': 'Teammedlem', 'verbose_name_plural': 'Teammedlemmar'},
        ),
    ]
