# Generated by Django 5.2.8 on 2025-11-12 12:42

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_alter_teammember_options'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='teampage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Hero-bild'),
        ),
        migrations.AlterField(
            model_name='teampage',
            name='about_content',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Om oss-innehåll'),
        ),
    ]
