# Generated by Django 5.2.8 on 2025-11-21 14:39

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0009_teampage_hero_video'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teampage',
            name='about_content',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('video', 3), ('quote', 4), ('team_highlight', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'help_text': 'Stor rubrik', 'icon': 'title', 'label': 'Rubrik'}), 1: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Löpande text', 'label': 'Text'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Lägg till bild', 'label': 'Bild'}), 3: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Team-intervju, culture video, office tour etc', 'icon': 'media', 'label': 'Video'}), 4: ('wagtail.blocks.BlockQuoteBlock', (), {'help_text': 'Blockquote/citat', 'label': 'Citat'}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'T.ex. "Våra värderingar"', 'label': 'Rubrik'}), 6: ('wagtail.blocks.RichTextBlock', (), {'label': 'Text'}), 7: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Optional video för detta highlight', 'label': 'Video (optional)', 'required': False}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Bild (optional)', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('title', 5), ('text', 6), ('video', 7), ('image', 8)]], {'help_text': 'Highlight-sektion med text + optional media', 'icon': 'group', 'label': 'Team Highlight'})}, help_text='Flexibelt innehåll för Om oss-sektionen. Lägg till videos, text, bilder i valfri ordning!', verbose_name='Om oss-innehåll'),
        ),
        migrations.AlterField(
            model_name='teampage',
            name='hero_video',
            field=models.ForeignKey(blank=True, help_text='Optional: Video för hero-bakgrund', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Hero video'),
        ),
        migrations.AlterField(
            model_name='teampage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, help_text='Kort intro-text som visas under hero', verbose_name='Introduktion'),
        ),
    ]
