# Generated by Django 5.0.14 on 2025-10-28 14:47

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Introduktion')),
                ('address', models.TextField(blank=True, verbose_name='Adress')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-post')),
                ('opening_hours', wagtail.fields.RichTextField(blank=True, help_text='T.ex. Mån-Fre: 08:00-17:00', verbose_name='Öppettider')),
                ('gdpr_text', wagtail.fields.RichTextField(default='Jag godkänner att mina uppgifter behandlas enligt GDPR', verbose_name='GDPR-text')),
            ],
            options={
                'verbose_name': 'Kontaktsida',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Namn')),
                ('email', models.EmailField(max_length=254, verbose_name='E-post')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='Ämne')),
                ('message', models.TextField(verbose_name='Meddelande')),
                ('gdpr_consent', models.BooleanField(default=False, verbose_name='GDPR-samtycke')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Inskickat')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='contact.contactpage')),
            ],
            options={
                'verbose_name': 'Kontaktförfrågan',
                'verbose_name_plural': 'Kontaktförfrågningar',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
