# Generated by Django 5.2.8 on 2025-12-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contactpage_hero_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='org_number',
            field=models.CharField(blank=True, help_text='Kundens organisationsnummer (valfritt).', max_length=32, verbose_name='Organisationsnummer'),
        ),
    ]
