# Generated by Django 5.0.14 on 2025-10-28 14:47

import django.db.models.deletion
import django.utils.timezone
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Introduktion')),
            ],
            options={
                'verbose_name': 'Blogg',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Publiceringsdatum')),
                ('author_name', models.CharField(blank=True, help_text='Ange författarens namn', max_length=255, verbose_name='Författare')),
                ('intro', models.CharField(help_text='Kort sammanfattning (visas i listningar och SEO)', max_length=250, verbose_name='Ingress')),
                ('body', wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='title', label='Rubrik')), ('paragraph', wagtail.blocks.RichTextBlock(label='Paragraf')), ('image', wagtail.images.blocks.ImageChooserBlock(label='Bild')), ('quote', wagtail.blocks.BlockQuoteBlock(label='Citat'))], verbose_name='Innehåll')),
            ],
            options={
                'verbose_name': 'Blogginlägg',
                'verbose_name_plural': 'Blogginlägg',
            },
            bases=('wagtailcore.page',),
        ),
    ]
