# Generated by Django 5.0.14 on 2025-10-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='reading_time',
            field=models.IntegerField(default=5, help_text='Uppskattad läsningstid i minuter', verbose_name='Läsningstid (minuter)'),
        ),
    ]
