# Generated by Django 5.2.8 on 2025-11-12 12:42

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogindexpage_hero_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogindexpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
