# Generated by Django 5.2.8 on 2025-11-21 14:39

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogindexpage_hero_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('quote', 3), ('video', 4)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'label': 'Rubrik'}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Paragraf'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Bild'}), 3: ('wagtail.blocks.BlockQuoteBlock', (), {'label': 'Citat'}), 4: ('wagtail.documents.blocks.DocumentChooserBlock', (), {})}, verbose_name='Innehåll'),
        ),
    ]
