# Generated by Django 5.2.8 on 2025-12-15 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blogpost_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('unsubscribe_token', models.CharField(editable=False, max_length=64, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='send_notification',
            field=models.BooleanField(default=True, help_text='Om ikryssad skickas mail till prenumeranter när inlägget publiceras första gången.', verbose_name='Skicka prenumerationsmail'),
        ),
        migrations.CreateModel(
            name='BlogPostNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_entry', to='blog.blogpost')),
            ],
        ),
    ]
